-- Employees
CREATE TABLE IF NOT EXISTS `itb_ivanova_employees` (
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `AGE` INT(10) NOT NULL,
    `GENDER` VARCHAR(20) NOT NULL DEFAULT 'unknown',
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`)
);

-- Employee Profiles
CREATE TABLE IF NOT EXISTS `itb_ivanova_employee_profiles` (
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
    `PHONE` VARCHAR(20),
    `EMAIL` VARCHAR(255) NOT NULL UNIQUE,
    `ADDRESS` TEXT,
    `EMPLOYEE_ID` INT(255) NOT NULL,
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`)
);

-- Tasks
CREATE TABLE IF NOT EXISTS `itb_ivanova_tasks` (
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `PRIORITY` INT (1),
    `DESC` LONGTEXT,
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'pending',
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `IS_ARCHIVED` VARCHAR(1) NOT NULL DEFAULT 'N',
    `EMPLOYEE_ID` INT(255) NOT NULL,
    PRIMARY KEY (`ID`)
);