CREATE TABLE IF NOT EXISTS `imlera_todo_employees` (
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `AGE` INT(10) NOT NULL,
    `GENDER` VARCHAR(20) NOT NULL DEFAULT 'unknown',
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `imlera_todo_profile` (
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
    `PHONE` VARCHAR(20),
    `EMAIL` VARCHAR(255) NOT NULL UNIQUE,
    `EMPLOYEE_ID` INT(10) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `imlera_todo_dt_employee_profile` (
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
    `EDIT_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `PROFILE_ID` INT(10) NOT NULL,
    `EMPLOYEE_ID` INT(10) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `imlera_todo_tasks` (
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `DESC` LONGTEXT,
    `PRIORITY` INT (1),
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'pending',
    `CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `EDIT_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `IS_ARCHIVED` VARCHAR(1) NOT NULL DEFAULT 'N',
    `EMPLOYEE_ID` INT(255) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `imlera_todo_fk_tasks` (
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
    `TASK_ID` INT(10) NOT NULL,
    `SUB_TASK_ID` INT(10) NOT NULL,
    PRIMARY KEY (`ID`)
)